config/routes.rb
Rails.application.routes.draw do
  
  resources :employees

  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
	get 'employeelogin' => :employeenew
	post 'employeelogin' => :employeecreate
	get 'employeelogout' => :employeedestroy
	delete 'employeelogout' => :employeedestroy
  end

  get 'pages/home'

  get 'pages/about'
  
  get '/all_customers' => 'customers#all_customers'
  

  resources :cards

  resources :accounts

  resources :customers

  root 'pages#home'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :accounts, dependent: :destroy
	
	has_secure_password
	
	validates :firstname, presence: true
	validates :lastname, presence: true
	validates :address, presence: true
	validates :city, presence: true
	validates :country, presence: true
	validates :telephone, presence: true
	validates :telephone, format: {with: /\(?(08)\)?(\d{1})\)?[- ]?(\d{3})[- ]?(\d{4})/, message: "Wrong format"}
	validates :email, presence: true
	validates :email, uniqueness: true
	validates :email, format: {with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/}
	validates :password, presence: true
	validates :password_confirmation, presence: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :authorise
  
  before_action :authorise, :except => :create
  before_action :authorise, :except => :new
  #before_action :authorise, :except => :all_customers

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
	@customer = @current_customer
  end
  
  #Displays all customers of the bank. Will only be availible to the ADMIN
  def all_customers
	@customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:firstname, :middlename, :lastname, :date_of_birth, :telephone, :address, :city, :country, :email, :password, :password_confirmation)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= bootstrap_form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
	<div class = "container">
		<div class ="row">
			<div class="col-md-3">
					
				<%= f.text_field :firstname %>
				<%= f.text_field :middlename %>
				<%= f.text_field :lastname %>
				<%= f.date_select :date_of_birth %>
				<%= f.text_field :telephone, placeholder: '0851234567'  %>
				<%= f.text_field :address %>
				<%= f.text_field :city %>
				<%= f.text_field :country %>
				<%= f.text_field :email %>
				<%= f.password_field :password %>
				<%= f.password_field :password_confirmation %>
				<div class="actions">
					<%= f.submit %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/customers/all_customers.html.erb
<h1>Listing customers</h1>


<div id = "tables">
	<table style="width:100%">
	  <thead>
		<tr>
		  <th>Customer ID</th>
		  <th>Firstname</th>
		  <th>Middlename</th>
		  <th>Lastname</th>
		  <th>Date of birth</th>
		  <th>Telephone</th>
		  <th>Address</th>
		  <th>City</th>
		  <th>Country</th>
		  <th>Email</th>
		  <th>Password Digest</th>
		  <th colspan="3"></th>
		</tr>
	  </thead>

	  <tbody>
		<% @customers.each do |customer| %>
		  <tr>
			<td><%= customer.id %></td>
			<td><%= customer.firstname %></td>
			<td><%= customer.middlename %></td>
			<td><%= customer.lastname %></td>
			<td><%= customer.date_of_birth %></td>
			<td><%= customer.telephone %></td>
			<td><%= customer.address %></td>
			<td><%= customer.city %></td>
			<td><%= customer.country %></td>
			<td><%= customer.email %></td>
			
			<!-- <td><%= customer.password_digest %></td> -->
			<td><%=  %> <!-- empty line so that the SHOW button doesnt move -->
			
			<td><%= link_to 'Show', customer %></td>
			<td><%= link_to 'Edit', edit_customer_path(customer) %></td>
			<td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		  </tr>
		<% end %>
	  </tbody>
	</table>
</div>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @current_customer %> |
<%= link_to 'Back', @current_customer %>

app/views/customers/index.html.erb
<h1>Your details:</h1>

<div class ="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<!-- Default panel contents -->
			<div class="panel-heading">
				<strong>Your details</strong>
			</div>

			<!-- Table -->
			<table class="table">
				<table style="width:100%">
					<thead>
						<tr>
							<th>Customer ID</th>
							<th>Firstname</th>
							<th>Middlename</th>
							<th>Lastname</th>
							<th>Date of birth</th>
							<th>Telephone</th>
							<th>Address</th>
							<th>City</th>
							<th>Country</th>
							<th>Email</th>
							<th>Password Digest</th>
							<th colspan="3"></th>
						</tr>
					</thead>

					<tbody>
						<tr>
							<td><%= @current_customer.id %></td>
							<td><%= @current_customer.firstname %></td>
							<td><%= @current_customer.middlename %></td>
							<td><%= @current_customer.lastname %></td>
							<td><%= @current_customer.date_of_birth %></td>
							<td><%= @current_customer.telephone %></td>
							<td><%= @current_customer.address %></td>
							<td><%= @current_customer.city %></td>
							<td><%= @current_customer.country %></td>
							<td><%= @current_customer.email %></td>
							
							<!-- <td><%= @current_customer.password_digest %></td> -->
							<td><%=  %> <!-- empty line so that the SHOW button doesnt move -->
							
							<td><%= link_to 'Show', @current_customer %></td>
							<td><%= link_to 'Edit', edit_customer_path(@current_customer) %></td>
							<td><%= link_to 'Destroy', @current_customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
						</tr>
					</tbody>
				</table>
			</table>
		</div>
	</div>
</div>
<br>
<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<div class = "container">
	<div class ="row">
		<div class="col-md-3">
			<div class="panel panel-default">
				<!-- Default panel contents -->
				<div class="panel-heading">
					<strong>Your details:</strong>
				</div>

				<!-- Table -->
				<table class="table">
					<table style="width:100%">
						<tbody>
							<tr>
								<td><strong>Customer number:</strong></td>
								<td><%= @customer.id %></td>
							</tr>
							<tr>
								<td><strong>Firstname:</strong></td>
								<td><%= @customer.firstname %></td>
							</tr>
							<tr>
								<td><strong>Middlename:</strong></td>
								<td><%= @customer.middlename %></td>
							</tr>
							<tr>
								<td><strong>Lastname:</strong></td>
								<td><%= @customer.lastname %></td>
							</tr>
							<tr>
								<td><strong>Date of birth:</strong></td>
								<td><%= @customer.date_of_birth %></td>
							</tr>
							<tr>
								<td><strong>Telephone:</strong></td>
								<td><%= @customer.telephone %></td>
							</tr>
							<tr>
								<td><strong>Address:</strong></td>
								<td><%= @customer.address %></td>
							</tr>
							<tr>
								<td><strong>City:</strong></td>
								<td><%= @customer.city %></td>
							</tr>
							<tr>
								<td><strong>Country:</strong></td>
								<td><%= @customer.country %></td>
							</tr>
							<tr>
								<td><strong>E-mail:</strong></td>
								<td><%= @customer.email %></td>
							</tr>
							<tr>
								<td><strong>Password digest:</strong></td>
								<td> <!-- <%= @customer.password_digest %> --> </td>
							</tr>
						</tbody>
					</table>
				</table>
			</div>
		</div>
	</div>

	<div class ="row">
		<div class="col-md-5">
			<div class="panel panel-default">
				<!-- Default panel contents -->
				<div class="panel-heading">
					<div class="field">
						<strong>Your accounts:</strong>
					</div>
				</div>
				
				<!-- Table -->
				<table class="table">
					<table style="width:100%">
						<thead>
							<tr>
								<th>Account Number</th>
								<th>Type</th>
								<th>Balance</th>
								<th colspan="3"></th>
							</tr>
						</thead>
						<tbody>
							<% @customer.accounts.each do |account| %>
								<tr>
									<td><%= account.id %></td>
									<td><%= account.account_type %></td>
									<td>$<%= account.balance %></td>
									<td><%= link_to 'Show', account %></td>
									<td><%= link_to 'Edit', edit_card_path(account) %></td>
									<td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</table>
			</div>
		</div>
	</div>
</div>
	
<% if signed_in? %>
	<%= link_to 'New Account', new_account_path %> |
	<%= link_to 'Edit your details', edit_customer_path(@current_customer) %>
<% else %>
<% end %>